#!/bin/bash

# =========================
# SYSTEM HEALTH CHECK SCRIPT
# Created Date =
# Modification =
# purpose =
# author =
# =========================

SERVICE="nginx"
FILE="/etc/passwd"
DIR="/tmp"
CPU=85

echo "===== SYSTEM CHECK START ====="

# 1. FILE CHECK
if [ -f "$FILE" ]
then
    echo "File exists: $FILE"
else
    echo "File not found"
fi

# 2. DIRECTORY CHECK
if [ -d "$DIR" ]
then
    echo "Directory exists: $DIR"
else
    echo "Directory not found"
fi

# 3. CPU CHECK (AND condition)
if [ "$CPU" -gt 80 ] && [ "$CPU" -lt 90 ]
then
    echo "CPU Warning level"
else
    echo "CPU Normal/Critical level"
fi

# 4. USER CHECK (OR condition)
if [ "$USER" = "root" ] || [ "$USER" = "ubuntu" ]
then
    echo "User allowed: $USER"
else
    echo "User not allowed"
fi

# 5. SERVICE CHECK (real production style)
systemctl status $SERVICE > /dev/null 2>&1

if [ $? -eq 0 ]
then
    echo "$SERVICE is RUNNING"
else
    echo "$SERVICE is STOPPED"
fi
-----------------------------------------------------------------
we can write for loop in 3 different ways
1. list style
for file in app.log nginx.log

2. command style
for pod in $(kubectl get pods -o name)

3. Range style
for i in {1..5}

Below are the -flags which we can use in for conditions.
-z empty
-n not empty
-f file
-d dir

sting logic(=,>,<,=!) and numeric logic(-gt, -ge, -eq, lt)
if you want to do same job on different resources we can use for loop
FOR loop means: "ek ek item uthao aur same kaam karo"

type of loops:
for loop = same work multiple items/list pe karo
while loop = jab tak condition true hai run karo
until loop = jab tak condition false hai run karo

there are 3 ways to use those loops in a format.
1. [condition]
example:
count=1

while [ $count -le 5 ]
do
   echo $count
   count=$((count+1))
done

2. command
example:
while ! systemctl is-active nginx > /dev/null 2>&1
do
   echo "waiting..."
   sleep 5
done

3. infinite loop true
example:
while true
do
   date
   sleep 2
done


echo "===== SYSTEM CHECK END ====="
